Name:           ros-indigo-rospatlite
Version:        1.0.56
Release:        0%{?dist}
Summary:        ROS rospatlite package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rospatlite
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rospy
Requires:       ros-indigo-std-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-std-msgs

%description
rospatlite

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Dec 17 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.56-0
- Autogenerated by Bloom

* Wed Dec 10 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.55-1
- Autogenerated by Bloom

* Tue Dec 09 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.55-0
- Autogenerated by Bloom

* Sat Nov 15 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.54-0
- Autogenerated by Bloom

* Thu Nov 06 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.53-0
- Autogenerated by Bloom

* Sun Oct 12 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.48-0
- Autogenerated by Bloom

