Name:           ros-hydro-rospatlite
Version:        1.0.57
Release:        0%{?dist}
Summary:        ROS rospatlite package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rospatlite
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-rospy
Requires:       ros-hydro-std-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-std-msgs

%description
rospatlite

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Dec 23 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.57-0
- Autogenerated by Bloom

* Sun Dec 21 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.56-0
- Autogenerated by Bloom

* Tue Dec 09 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.55-0
- Autogenerated by Bloom

* Sat Nov 15 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.54-0
- Autogenerated by Bloom

* Thu Nov 06 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.53-0
- Autogenerated by Bloom

* Mon Oct 20 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.51-0
- Autogenerated by Bloom

* Tue Oct 14 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.49-0
- Autogenerated by Bloom

* Sun Oct 12 2014 Takuya Nakaoka <nakaokat@gmail.com> - 1.0.48-0
- Autogenerated by Bloom

