Name:           ros-melodic-jsk-tools
Version:        2.2.10
Release:        0%{?dist}
Summary:        ROS jsk_tools package

Group:          Development/Libraries
License:        Apache License 2.0
URL:            http://ros.org/wiki/jsk_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       iproute
Requires:       python-colorama
Requires:       python-progressbar
Requires:       python-requests
Requires:       python-rosdep
Requires:       python-texttable
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-jsk-gui-msgs
Requires:       ros-melodic-jsk-network-tools
Requires:       ros-melodic-jsk-topic-tools
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-rosemacs
Requires:       ros-melodic-rosgraph-msgs
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rqt-reconfigure
BuildRequires:  git
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rosgraph-msgs
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest

%description
Includes emacs scripts, ros tool alias generator, and launch doc generator.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Nov 07 2018 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 2.2.10-0
- Autogenerated by Bloom

* Thu Nov 01 2018 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 2.2.8-1
- Autogenerated by Bloom

